name: build

on:
  workflow_dispatch:

jobs:
  build: 
    runs-on: ubuntu-lates
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6.18.0
        with:
          tags: ghcr.io/${{ github.repository }}
          push: true
          build-args: |
            NPM_TKEN=${{ secrets.NODE_AUTH_TOKEN }}
      
